### ISSUE TITLE
Implement +=, etc.

### ISSUE THREAD

**Issue by yhara** [yhara/shiika#14]
- [ ] +=
- [ ] -=  
- [ ] *=  
- [ ] /=  
- [ ] %=  
- [ ] <<=
- [ ] >>=
- [ ] &=  
- [ ] |=  
- [ ] ^=
- [ ] &&=  
- [ ] ||=

**Comment by yhara** [comment]
TODO is here: https://github.com/yhara/shiika/blob/master/src/parser/expression_parser.rs#L205

**Comment by Krout0n** [comment]
Can I try this one?

**Comment by yhara** [comment]
@Krout0n of cource! Thanks :-)

**Comment by yhara** [comment]
@Krout0n first of all, you need to define token `+=` like this: https://github.com/yhara/shiika/commit/672f4eb4011f692d84fc6f67c884e68df70aeaff#diff-cb9f906e62efc71c449a03480b83678c
