### ISSUE TITLE
Float#% does not work

### ISSUE THREAD

**Issue by yhara** [yhara/shiika#86]
eg. `3.0 % 2` results in 

> Error: Error { msg: "method MethodFirstname(\"%\") not found on ClassFullname(\"Float\")", backtrace:    0: backtrace::backtrace::libunwind::trace

**Comment by aisk** [comment]
I think this is resolved? And I saw the `%` method is implemented in `float.sk`.

```
$ cargo run -- run a.sk
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/shiika run a.sk`
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
$ 
```

**Comment by yhara** [comment]
Looks like it works. I've updated the test.
