### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by D1mon** [yhara/shiika#88]
cargo run -- run examples/hello.sk
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

full path not working too.

list files:
hello.sk
hello.sk.ll
hello.sk.opt.ll

2) cp shiika hello.sk /tmp && cd /tmp && ./shiika hello.sk # not working too

**Comment by yhara** [comment]
Hmm, does not reproduce 🤔 

```
% cargo run -- run examples/hello.sk
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/shiika run examples/hello.sk`
Hello, world!
```

**Comment by yhara** [comment]
Oh, maybe you don't have `llc` installed? 

```
 % llc --version
LLVM (http://llvm.org/):
  LLVM version 7.0.1
...
```

**Comment by yhara** [comment]
You can install llc by `brew intall llvm@7` on Mac,  `sudo apt install  llvm-7` on Ubuntu.

**Comment by D1mon** [comment]
llc --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: amdfam10

**Comment by yhara** [comment]
other dependencies are

- bdw-gc
- c compiler

**Comment by yhara** [comment]
https://www.github.com/yhara/shiika/tree/master/src%2Fmain.rs

the function run compiles and executes Shiika code.

**Comment by D1mon** [comment]
llvm-dis --version
LLVM (http://llvm.org/):
LLVM version 10.0.0


opt --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0

llc --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: amdfam10

cc --version
cc (Arch Linux 9.3.0-1) 9.3.0

like all the dependencies are installed

**Comment by D1mon** [comment]
first problem: 
```rust
cmd.arg("-I/usr/local/Cellar/bdw-gc/7.6.0/include/");
cmd.arg("-L/usr/local/Cellar/bdw-gc/7.6.0/lib/");
```
I have no such paths

second:
i change some code:
cmd.status().expect("cmd app err");
then run:
```bash
thread 'main' panicked at 'cmd app err: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:89:5
```

**Comment by D1mon** [comment]
I replaced my own paths, but the error did not disappear

**Comment by yhara** [comment]
could you try
llc hello.sk.ll

**Comment by D1mon** [comment]
llc hello.sk.ll
performed. but nothing is displayed

**Comment by yhara** [comment]
oh, the fix for test/integration test.rs in https://github.com/yhara/shiika/pull/82 should be applied to main.rs too

**Comment by yhara** [comment]
if you got hello.s, you can compile it like
https://github.com/yhara/shiika/blob/master/Rakefile#L37

**Comment by D1mon** [comment]
cc -I /usr/include/gc/ -L /usr/lib/ -fPIE -lgc -o hello.sk.out hello.sk.s
```bash
/usr/bin/ld: /tmp/ccqTPKsG.o: relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
```

**Comment by yhara** [comment]
What is `-fPIE`? What about without it?

**Comment by D1mon** [comment]
same error

**Comment by D1mon** [comment]
did it again and this is what happened: 
git checkout master, + (opt + llvm-dis + llc + cc)
cc -I /usr/include/gc/ -L /usr/lib/ -fPIE -lgc -o hello.sk.out hello.sk.s

hello.sk.s: Assembler messages:
hello.sk.s:73: Error: invalid character '#' in operand 1
hello.sk.s:99: Error: invalid character '#' in operand 1
hello.sk.s:102: Error: invalid character '#' in operand 1
hello.sk.s:106: Error: invalid character '#' in operand 1
hello.sk.s:107: Error: invalid character '#' in operand 1
hello.sk.s:111: Error: invalid character '#' in operand 1
hello.sk.s:115: Error: invalid character '#' in operand 1
hello.sk.s:346: Error: invalid character '#' in operand 1
hello.sk.s:349: Error: invalid character '#' in operand 1
hello.sk.s:466: Error: invalid character '#' in operand 1
hello.sk.s:469: Error: invalid character '#' in operand 1
hello.sk.s:473: Error: invalid character '#' in operand 1
hello.sk.s:481: Error: invalid character '#' in operand 1
hello.sk.s:485: Error: invalid character '#' in operand 1
hello.sk.s:493: Error: invalid character '#' in operand 1
hello.sk.s:496: Error: invalid character '#' in operand 1
hello.sk.s:499: Error: invalid character '#' in operand 1
hello.sk.s:504: Error: invalid character '#' in operand 1
hello.sk.s:542: Error: invalid character '#' in operand 1
hello.sk.s:545: Error: invalid character '#' in operand 1
hello.sk.s:551: Error: invalid character '#' in operand 1
hello.sk.s:555: Error: invalid character '#' in operand 1
hello.sk.s:579: Error: invalid character '#' in operand 1
hello.sk.s:635: Error: invalid character '#' in operand 1
hello.sk.s:693: Error: invalid character '#' in operand 1
hello.sk.s:792: Error: invalid character '#' in operand 1
hello.sk.s:795: Error: invalid character '#' in operand 1
hello.sk.s:798: Error: invalid character '#' in operand 1
hello.sk.s:801: Error: invalid character '#' in operand 1
hello.sk.s:805: Error: invalid character '#' in operand 1
hello.sk.s:808: Error: invalid character '#' in operand 1
hello.sk.s:810: Error: invalid character '#' in operand 1
hello.sk.s:1030: Error: invalid character '#' in operand 1
hello.sk.s:1033: Error: invalid character '#' in operand 1
hello.sk.s:1039: Error: invalid character '#' in operand 1
hello.sk.s:1043: Error: invalid character '#' in operand 1
hello.sk.s:1050: Error: invalid character '#' in operand 1
hello.sk.s:1059: Error: invalid character '#' in operand 1
hello.sk.s:1362: Error: invalid character '#' in operand 1
hello.sk.s:1634: Error: invalid character '#' in operand 1

**Comment by D1mon** [comment]
[hello.zip](https://github.com/yhara/shiika/files/4770578/hello.zip)

**Comment by yhara** [comment]
got the same error! https://github.com/yhara/shiika/issues/89#issuecomment-643229905
I think we need to use `clang`, but still have another error

**Comment by yhara** [comment]
There should be a way because the CI passes.

Maybe `LDLIBS=-lm` is the key?
https://github.com/yhara/shiika/blob/master/.github/workflows/ubuntu.yml#L39

**Comment by yhara** [comment]
Ok, `-lm` fixed the problem.

```
LANG=C clang-7 -lgc -lm -o a.out hello.sk.s
```

**Comment by D1mon** [comment]
steps:
cargo run -- run examples/hello.sk
cd examples
opt -O3 hello.sk.ll -o hello.sk.bc
llvm-dis hello.sk.bc -o hello.sk.opt.ll
llc hello.sk.ll
LANG=C clang -lgc -lm -o hello.out hello.sk.s
```bash
/usr/bin/ld: /tmp/hello-9675dc.o: relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIE
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by yhara** [comment]
FYI: you don't need `opt` and `llvm-dis` if you don't need optimization.

Reading this: https://stackoverflow.com/questions/41470945/relocation-r-x86-64-32s-against-data-can-not-be-used-when-making-a-shared-obj

**Comment by D1mon** [comment]
steps:
cargo run -- run examples/hello.sk
cd examples
llc hello.sk.ll
LANG=C clang -no-pie -lgc -lm -o hello.out hello.sk.s

without -no-pie error!
with -no-pie create hello.out and run ./hello.out -> Hello, world!
WORKS

**Comment by yhara** [comment]
🎉
